### ISSUE TITLE
Installer / Uninstaller

### ISSUE THREAD

**Issue by GoogleCodeExporter** [msofficesvn/msofficesvn#24]
```
Can anyone write a installer/uninstaller that copies/deletes the files.
Thanks!
```

Original issue reported on code.google.com by `bernhard...@mt.com` on 4 Jun 2012 at 4:44

**Comment by justinmassiot** [comment]
Because of a long period of inactivity since the original submission of this issue, I'm closing this ticket.
I can't recover the installer files because the files aren't accessible any more...
