### ISSUE TITLE
Runtime Error 4248 occurs when enable editing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [msofficesvn/msofficesvn#28]
```
What steps will reproduce the problem?
1. Open a word document file on a server by Word 2010.
2. Click Enable Editing button above the document.
3. Runtime Error 4248 occurs.

What is the expected output? What do you see instead?


Please use labels and text to provide additional information.


```

Original issue reported on code.google.com by `kok...@gmail.com` on 14 Jul 2014 at 4:36

Attachments:
- [word_runtime_error_4248.png](https://storage.googleapis.com/google-code-attachments/msofficesvn/issue-28/comment-0/word_runtime_error_4248.png)

**Comment by justinmassiot** [comment]
Because of a long period of inactivity since the original submission of this issue, I'm closing this ticket.
