### ISSUE TITLE
Error loading pptsvn in Powerpoint 2016

### ISSUE THREAD

**Issue by rjkantor** [msofficesvn/msofficesvn#29]
C:\Users\<username>\AppData\Roaming\Microsoft\AddIns\pptsvn.ppam is not a valid Office Add-in.

Please advise.  The Excel and Word loaded without issue.

**Comment by rjkantor** [comment]
It seems if you load the ppam using File | Open it loads into the ribbon. but does not persist beyond the session.  

Please advise how to persist for every load of powerpoint.

**Comment by justinmassiot** [comment]
Hey @rjkantor,

1. From what place did you download the binary files?
1. Are you sure to have applied what is said in the [installation instructions](https://github.com/kokiya/msofficesvn/blob/wiki/Install.md)?

I've just added the ribbon without any issue to my PowerPoint 2019, just [like I did with MS Office 2016](https://gotomation.info/2019/01/svn-version-control-office-documents/#a-quick-insight-of-msofficesvn) for example.

**Comment by rjkantor** [comment]
Yes I followed the direction.  I redownloaded from your site.  I was only able to do a file | open and then it loaded in ppt.  If I try to add the add in it keeps telling me the file is not a valid addin.   The other two worked as described.

Robb

**Comment by justinmassiot** [comment]
Could you please describe what exact steps do you follow to add the add-in from PowerPoint?

This should look like this:

![image](https://user-images.githubusercontent.com/11060755/86779072-6955a980-c05b-11ea-93d8-5964388a27a0.png)
![image](https://user-images.githubusercontent.com/11060755/86779112-74a8d500-c05b-11ea-96a2-b51f81baaf35.png)

**Comment by rjkantor** [comment]
At the bottom where you show “powerpoint addins”, my was showing com addins.  Let me check to see if I can change that.  Will let you know.

Thank you,
Robb

**Comment by justinmassiot** [comment]
@rjkantor , is your problem solved?

**Comment by rjkantor** [comment]
Yes, that was the issue.  I appreciate the guidance.



Robb






---- On Thu, 09 Jul 2020 03:55:40 -0400 Justin MASSIOT <notifications@github.com> wrote ----




https://github.com/rjkantor , is your problem solved?

**Comment by justinmassiot** [comment]
Nice to hear that, thanks for the feedback.
