### ISSUE TITLE
Add-in does not remain in Excel 2016

### ISSUE THREAD

**Issue by goldrhim** [msofficesvn/msofficesvn#31]
Hello,

I installed the add-ins for Word, Excel and PowerPoint.  For Word and PowerPoint, the ribbon bar entry remains even after I close the application and reopen it. For Excel, after I add the add-in, the tab appears in the ribbon bar, but as soon as I close Excel and re-open it, the tab is no longer there.

As far as I can tell, Excel is not disabling the add-in (it's not in the "disabled" list).  Anyone else experiencing this?

**Comment by justinmassiot** [comment]
Hi!
Never seen this on my side, neither in 2016 nor in 2019.
Are the `*.ini` and `*.xlam` files still present in the correct folder after having closed Excel?

**Comment by goldrhim** [comment]
Thanks for the reply.

Yes, in fact I can simply add it again and it works until I close Excel.

**Comment by justinmassiot** [comment]
Then I'm not sure how I can help you more...

**Comment by goldrhim** [comment]
Thanks, I actually found the solution... the files were marked as "blocked" by Windows (in the properties of the file). Once unblocking them, it works fine.

https://jkp-ads.com/articles/excel-add-ins-fail-to-load.asp

**Comment by justinmassiot** [comment]
Great to read that!
Thanks for coming back with the solution you found.
